name: test_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.0.1
  - mlflow=2.2.2
  - pandas=1.5.3
  - scikit-learn=1.2.1
  - numpy=1.23.5
  - matplotlib=3.6.3
  - seaborn=0.12.2
  - pip:
    - wandb==0.14.0