name: risk_assessment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.13
  - ipython=8.11.0
  - mlflow=2.2.2
  - hydra-core=1.3.2
  - google-cloud-storage=2.7.0
  - pip=23.0.1
  - pip:
      - wandb==0.14.0
      - python-decouple==3.8